# fly.toml app configuration file generated for kadreg on 2025-09-23T22:15:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kadreg'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8621
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
