------------------------------
-- Members
------------------------------

CREATE TYPE member_role AS ENUM ('Member', 'Staff', 'RegStaff', 'Director', 'Sysadmin');

CREATE TABLE members (
    membership_num INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email_address TEXT NOT NULL,
    handle TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    emergency_contact TEXT,
    role member_role NOT NULL DEFAULT 'Member',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- Enforce uniqueness of email_address for non-deleted members
CREATE UNIQUE INDEX idx_members_email_active
    ON members (email_address)
    WHERE deleted_at IS NULL;

-- Efficiently list all members of a given role
CREATE INDEX idx_members_role ON members (role);

-- Automatically update updated_at column on row modification
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_members_updated_at
    BEFORE UPDATE ON members
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

------------------------------
-- Admin audit log
------------------------------

CREATE TYPE admin_action_type AS ENUM ('update_member', 'delete_member');

CREATE TABLE admin_audit_log (
    audit_id BIGSERIAL PRIMARY KEY,
    performed_by INTEGER NOT NULL REFERENCES members(membership_num),
    action_type admin_action_type NOT NULL,
    target_member INTEGER NOT NULL REFERENCES members(membership_num),
    old_values JSONB,
    new_values JSONB,
    performed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for querying by admin who performed the action
CREATE INDEX idx_admin_audit_performed_by ON admin_audit_log (performed_by);

-- Index for querying by target member
CREATE INDEX idx_admin_audit_target_member ON admin_audit_log (target_member);

-- Index for querying by time
CREATE INDEX idx_admin_audit_performed_at ON admin_audit_log (performed_at DESC);

------------------------------
-- Pending members
------------------------------

CREATE TABLE pending_members (
    email_address TEXT PRIMARY KEY,
    handle TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    email_confirm_token TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index by created_at to allow eventual deletion of never-confirmed members from before a certain date
CREATE INDEX idx_pending_members_created_at ON pending_members (created_at);

-- Prevent pending_members from having an email that exists in members
CREATE OR REPLACE FUNCTION check_pending_member_email()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM members
    WHERE email_address = NEW.email_address
    AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'An account with this email address already exists'
      USING ERRCODE = '23505'; -- unique_violation error code
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER prevent_duplicate_email_in_pending_members
  BEFORE INSERT ON pending_members
  FOR EACH ROW
  EXECUTE FUNCTION check_pending_member_email();

------------------------------
-- Registrations
------------------------------

CREATE TYPE registration_tier AS ENUM ('standard', 'sponsor', 'subsidised', 'double_subsidised');
CREATE TYPE registration_status AS ENUM ('pending', 'successful', 'paid', 'cancelled');

CREATE TABLE registrations (
    member_id INTEGER NOT NULL REFERENCES members(membership_num),
    convention_id TEXT NOT NULL,
    tier registration_tier NOT NULL,
    status registration_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (member_id, convention_id)
);

CREATE INDEX idx_registrations_convention ON registrations (convention_id);
CREATE INDEX idx_registrations_status ON registrations (convention_id, status);

CREATE TRIGGER update_registrations_updated_at
    BEFORE UPDATE ON registrations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
